name: template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.2.0
  get_it: ^6.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  injectable_generator: ^1.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  # Custom fonts files
  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/AppCustomFont.ttf

