name: Apk workflow

on:
  workflow_call:

jobs:
  e2e:
    name: Integration test
    strategy:
      matrix:
        api-level: [ 29 ]
      fail-fast: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test test/integration_test/app_test.dart --verbose

  build:
    needs: e2e
    name: Build Flutter App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter channel beta
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter config --enable-android
      - run: flutter create .
      - run: flutter build apk -t lib/main_dev.dart
      - run: flutter build appbundle -t lib/main_dev.dart
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk_build
          path: build/app

  deploy:
    name: Deploy app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: apk_build
          path: apk_build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@master
        with:
          appId: 1:420295022617:android:bc466a27c1a670834d3288
          token: 1//069zeH2EL8NWICgYIARAAGAYSNwF-L9IrWy9_03-PKJVkSJyV1zAoSmkZKoLlecYkqXcQedU1EshrwoBW7jCFX5t78aosc8QhONA
          groups: testers
          file: apk_build/outputs/apk/release/app-release.apk