name: Web workflow

on:
  workflow_call:

jobs:
  e2e:
    name: Integration test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: browser-actions/setup-chrome@latest
      - name: Run integration tests
        uses: nanasess/setup-chromedriver@v1
        with:
          channel: 'stable'
      - run: chromedriver --port=4444 &
      - run: flutter drive --driver=test/test_driver/integration_test.dart --target=test/integration_test/app_test.dart -d web-server

  build:
    needs: e2e
    name: Build Flutter App
    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.DEV_KEY }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.DEV_GOOGLE_MAPS_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
      - name: Creating .env file
        working-directory: ./
        run: |
          echo ${{ env.KEY }} >> .env
          echo ${{ env.GOOGLE_MAPS_API_KEY }} >> .env
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build web -t lib/main_dev.dart
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_build
          path: build/web

  deploy:
    name: Deploy Website
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: web_build
          path: web_build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
